### PR TITLE
update debug-toolbar

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by lmorchard** [comment]
Oof, this was a branch on the upstream repo rather than your fork. Having trouble pulling the branch down, for some reason. :confused:

Oh, never mind, seems to have let me fetch it now. Taking a look.

**Comment by lmorchard** [comment]
So, similar to [my comment over on the kuma PR](https://github.com/mozilla/kuma/pull/2072#discussion_r10125255), we're trying to move from git commits to released versions from pypi.

What would probably be better here is to [install the released version from pypi into the vendor lib](http://playdoh.readthedocs.org/en/latest/packages.html#non-git-based-repos-hg-cvs-tarball), rather than using a git submodule. More of a nitpick, though, since hopefully we're headed toward getting rid of kuma-lib altogether in the hopefully not distant future.

**Comment by groovecoder** [comment]
Since we're not quite playdoh, I think this process should work for us:

http://kuma.readthedocs.org/en/latest/vendor.html#updating-a-library-from-pypi

So, I would:
- [x] Update kuma `requirements/dev.txt` to install 1.0.1
- [x] Update this pull to include 1.0.1 code installed from pypi into vendor/src
- [x] Update this pull to ... remove the git submodule?

**Comment by groovecoder** [comment]
Hmm ... I tried to re-arrange this pull to install the released version from pypi but I'm not sure where to install it - i.e., `packages/` or `lib/python`?

**Comment by lmorchard** [comment]
Well, doing it using the Playdoh advice leaves it in `lib/python`, whereas our older docs leave it under `packages`. Either way is fine, I think? I want to say the Playdoh way is more Python-natural, but I'm fuzzy on this

**Comment by groovecoder** [comment]
If we're planning to dump this whole repo/submodule in the future, I'll just defer to whichever location @jezdez or @ubernostrum say is best. ;)

**Comment by lmorchard** [comment]
I don't think either really matters - we support both. I think you can just pick one.

**Comment by groovecoder** [comment]
Alright, I stuck it in `lib/python`. Should be good to go now.

**Pull request merged**
